name: Windows Installer

on:
  push:
    branches:
      - main
      - main-ci-test
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Qt 6.9 & Windows
    runs-on: windows-2025

    env:
      QT_VERSION: 6.9.0
      BUILD_DIR: r2s_build
      QT_MINGW: mingw1310_64

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: ${{ env.QT_VERSION }}
          arch: win64_mingw

      - name: List Qt directory
        run: Get-ChildItem -Recurse C:\Qt

      - name: Add MinGW to PATH
        run: |
          echo "C:\Qt\6.9.0\mingw_64\bin" | Out-File -FilePath $env:GITHUB_PATH -Append

      - name: Show compiler and Qt tools in PATH (debug)
        run: |
          echo "G++ :"
          where g++
          echo "qmake :"
          where qmake
          echo "mingw32-make :"
          where mingw32-make
          echo "cmake :"
          where cmake
          echo $env:PATH

      - name: Install CMake & Ninja
        uses: lukka/get-cmake@latest

      - name: Install 7-Zip
        run: choco install 7zip -y

      - name: Create build directory
        run: cmake -E make_directory ${{ env.BUILD_DIR }}

      - name: Configure CMake
        run: |
          cmake -S . -B ${{ env.BUILD_DIR }} -G "MinGW Makefiles" -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH="C:/Qt/${{ env.QT_VERSION }}/mingw_64"

      - name: Build
        run: |
          cmake --build ${{ env.BUILD_DIR }} --config Release

      - name: Install
        run: cmake --install ${{ env.BUILD_DIR }}
        shell: bash

      - name: Package build output as 7z
        run: |
          7z a build-output.7z .\${{ env.BUILD_DIR }}\*

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: roc2rawsplits.7z
          path: build-output.7z